# Generated by Django 6.0.6 on 2026-06-05 01:09

import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='活动名称')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='URL 标识')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '运行中'), ('paused', '已暂停'), ('ended', '已结束')], default='draft', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='活动描述')),
                ('utm_source', models.CharField(blank=True, max_length=120, verbose_name='UTM Source')),
                ('utm_medium', models.CharField(blank=True, max_length=120, verbose_name='UTM Medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=120, verbose_name='UTM Campaign')),
                ('auto_rule_enabled', models.BooleanField(default=False, verbose_name='启用自动规则')),
                ('target_countries', models.JSONField(blank=True, default=list, help_text="例如: ['US', 'GB', 'VN', 'TH']", verbose_name='目标国家')),
                ('target_page_pattern', models.CharField(blank=True, help_text='例如: /pricing/ 匹配所有定价页访问', max_length=200, verbose_name='目标页面匹配')),
                ('delay_minutes', models.PositiveIntegerField(default=10, verbose_name='延迟分钟数')),
                ('welcome_email_template', models.TextField(blank=True, verbose_name='欢迎邮件模板')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='预算 (USD)')),
                ('spent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='已花费 (USD)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '推广活动',
                'verbose_name_plural': '推广活动',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
                ('ip_hash', models.CharField(blank=True, db_index=True, help_text='SHA-256 哈希后的 IP，满足 GDPR 要求', max_length=64, verbose_name='IP 哈希 (GDPR)')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='国家/地区')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='城市')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='省/州')),
                ('timezone', models.CharField(blank=True, max_length=50, verbose_name='时区')),
                ('device_type', models.CharField(choices=[('mobile', '手机'), ('tablet', '平板'), ('desktop', '桌面'), ('other', '其他')], default='other', max_length=20, verbose_name='设备类型')),
                ('browser', models.CharField(blank=True, max_length=100, verbose_name='浏览器')),
                ('os', models.CharField(blank=True, max_length=100, verbose_name='操作系统')),
                ('referrer', models.URLField(blank=True, max_length=500, verbose_name='来源链接')),
                ('referrer_domain', models.CharField(blank=True, max_length=200, verbose_name='来源域名')),
                ('landing_page', models.CharField(blank=True, max_length=500, verbose_name='着陆页')),
                ('utm_source', models.CharField(blank=True, max_length=200, verbose_name='UTM Source')),
                ('utm_medium', models.CharField(blank=True, max_length=200, verbose_name='UTM Medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=200, verbose_name='UTM Campaign')),
                ('utm_term', models.CharField(blank=True, max_length=200, verbose_name='UTM Term')),
                ('utm_content', models.CharField(blank=True, max_length=200, verbose_name='UTM Content')),
                ('is_gdpr_region', models.BooleanField(default=False, help_text='是否来自 EU/EEA 或英国', verbose_name='GDPR 地区')),
                ('first_visited', models.DateTimeField(default=django.utils.timezone.now, verbose_name='首次访问')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='最近活跃')),
                ('visit_count', models.PositiveIntegerField(default=1, verbose_name='访问次数')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors', to='marketing.campaign', verbose_name='关联活动')),
            ],
            options={
                'verbose_name': '访客日志',
                'verbose_name_plural': '访客日志',
                'ordering': ['-first_visited'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='姓名')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='公司')),
                ('job_title', models.CharField(blank=True, max_length=200, verbose_name='职位')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='国家/地区')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='电话')),
                ('source', models.CharField(blank=True, help_text='website / youtube / linkedin / referral / event', max_length=100, verbose_name='来源')),
                ('stage', models.CharField(choices=[('new', '新线索'), ('contacted', '已联系'), ('qualified', '已确认'), ('converted', '已转化'), ('closed', '已关闭')], default='new', max_length=20, verbose_name='阶段')),
                ('interested_product', models.CharField(blank=True, max_length=200, verbose_name='感兴趣产品')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('contacted_at', models.DateTimeField(blank=True, null=True, verbose_name='联系时间')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='marketing.campaign', verbose_name='来源活动')),
                ('visitor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead', to='marketing.visitorlog', verbose_name='关联访客')),
            ],
            options={
                'verbose_name': '营销线索',
                'verbose_name_plural': '营销线索',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='visitorlog',
            index=models.Index(fields=['country'], name='marketing_v_country_f0c231_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorlog',
            index=models.Index(fields=['ip_hash'], name='marketing_v_ip_hash_dc0157_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorlog',
            index=models.Index(fields=['first_visited'], name='marketing_v_first_v_954910_idx'),
        ),
    ]
