# Generated by Django 6.0.6 on 2026-06-05 01:22

import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funnel_stage', models.CharField(default='L2', editable=False, max_length=2, verbose_name='漏斗层级')),
                ('engagement_type', models.CharField(choices=[('page_view', '页面浏览'), ('article_read', '文章阅读'), ('video_watch', '视频观看'), ('download', '资料下载'), ('scroll_80', '滚动至80%')], max_length=20, verbose_name='互动类型')),
                ('content_url', models.CharField(blank=True, max_length=500, verbose_name='内容 URL')),
                ('content_title', models.CharField(blank=True, max_length=300, verbose_name='内容标题')),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='停留超过 60s 视为有效兴趣', verbose_name='停留时长(秒)')),
                ('is_qualified', models.BooleanField(default=False, help_text='停留超过 60s 或下载/阅读完成标记为 True', verbose_name='有效互动')),
                ('device_type', models.CharField(blank=True, max_length=20, verbose_name='设备')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='国家/地区')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='互动时间')),
            ],
            options={
                'verbose_name': 'L2 内容互动',
                'verbose_name_plural': 'L2 内容互动',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailDrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='序列名称')),
                ('trigger', models.CharField(choices=[('visitor_welcome', 'L1 首次访问欢迎'), ('engagement_followup', 'L2 内容互动跟进'), ('lead_welcome', 'L3 新线索欢迎'), ('report_download', 'L3 下载行业报告'), ('abandoned_cart', 'L4 弃单挽回'), ('post_purchase', 'L5 购买感谢'), ('reengagement', '30天未活跃复购激活')], max_length=30, unique=True, verbose_name='触发条件')),
                ('subject_template', models.CharField(max_length=300, verbose_name='邮件主题模板')),
                ('body_template', models.TextField(help_text='可使用变量: {name}, {email}, {country}, {product_name}', verbose_name='邮件正文模板')),
                ('delay_hours', models.PositiveIntegerField(default=0, help_text='触发后延迟多久发送 (0 = 立即)', verbose_name='延迟小时数')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('include_unsubscribe', models.BooleanField(default=True, verbose_name='包含退订链接')),
                ('gdpr_compliant', models.BooleanField(default=True, verbose_name='GDPR 合规')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '邮件序列',
                'verbose_name_plural': '邮件序列',
                'ordering': ['trigger'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300, verbose_name='邮件主题')),
                ('status', models.CharField(choices=[('sent', '已发送'), ('delivered', '已送达'), ('opened', '已打开'), ('clicked', '已点击'), ('bounced', '退回'), ('unsubscribed', '已退订'), ('failed', '发送失败')], default='sent', max_length=20, verbose_name='发送状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='打开时间')),
                ('clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='点击时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '邮件日志',
                'verbose_name_plural': '邮件日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funnel_stage', models.CharField(default='L4', editable=False, max_length=2, verbose_name='漏斗层级')),
                ('intent_type', models.CharField(choices=[('pricing_view', '查看定价页'), ('add_to_cart', '加入购物车'), ('checkout_start', '开始结账'), ('trial_request', '申请试用'), ('consultation', '预约咨询'), ('demo_request', '申请演示')], max_length=20, verbose_name='意图类型')),
                ('product_name', models.CharField(blank=True, max_length=200, verbose_name='目标产品')),
                ('product_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='产品价格')),
                ('cart_items', models.JSONField(blank=True, default=list, verbose_name='购物车内容')),
                ('is_completed', models.BooleanField(default=False, verbose_name='已完成操作')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='国家/地区')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='触发时间')),
            ],
            options={
                'verbose_name': 'L4 商业意图',
                'verbose_name_plural': 'L4 商业意图',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funnel_stage', models.CharField(default='L5', editable=False, max_length=2, verbose_name='漏斗层级')),
                ('order_number', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='订单号')),
                ('product_name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='支付金额')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='币种')),
                ('payment_method', models.CharField(choices=[('paypal', 'PayPal'), ('stripe', 'Stripe / Card'), ('wechat', '微信支付'), ('alipay', '支付宝'), ('bank_transfer', '银行转账')], max_length=20, verbose_name='支付方式')),
                ('transaction_id', models.CharField(blank=True, help_text='PayPal / Stripe 返回的 Transaction ID', max_length=128, verbose_name='交易 ID')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='购买国家')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='是否为订阅')),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='支付时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'L5 付费订单',
                'verbose_name_plural': 'L5 付费订单',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at'], 'verbose_name': 'L3 营销线索', 'verbose_name_plural': 'L3 营销线索'},
        ),
        migrations.AlterModelOptions(
            name='visitorlog',
            options={'ordering': ['-first_visited'], 'verbose_name': 'L1 访客日志', 'verbose_name_plural': 'L1 访客日志'},
        ),
        migrations.RemoveField(
            model_name='visitorlog',
            name='timezone',
        ),
        migrations.AddField(
            model_name='lead',
            name='consent_marketing',
            field=models.BooleanField(default=False, help_text='用户明确勾选的营销同意', verbose_name='同意营销邮件'),
        ),
        migrations.AddField(
            model_name='lead',
            name='consent_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='同意时间'),
        ),
        migrations.AddField(
            model_name='lead',
            name='email_sent_discount',
            field=models.BooleanField(default=False, verbose_name='已发折扣'),
        ),
        migrations.AddField(
            model_name='lead',
            name='email_sent_report',
            field=models.BooleanField(default=False, verbose_name='已发行业报告'),
        ),
        migrations.AddField(
            model_name='lead',
            name='email_sent_welcome',
            field=models.BooleanField(default=False, verbose_name='已发欢迎邮件'),
        ),
        migrations.AddField(
            model_name='lead',
            name='funnel_stage',
            field=models.CharField(default='L3', editable=False, max_length=2, verbose_name='漏斗层级'),
        ),
        migrations.AddField(
            model_name='lead',
            name='source_page',
            field=models.CharField(blank=True, help_text='捕获线索的具体页面 URL', max_length=200, verbose_name='来源页面'),
        ),
        migrations.AddField(
            model_name='lead',
            name='unsubscribed',
            field=models.BooleanField(default=False, verbose_name='已退订'),
        ),
        migrations.AddField(
            model_name='lead',
            name='unsubscribed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='退订时间'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='consent_given',
            field=models.BooleanField(default=False, verbose_name='已授权追踪'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='funnel_stage',
            field=models.CharField(default='L1', editable=False, max_length=2, verbose_name='漏斗层级'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='timezone_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='时区'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('website', '官网'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('referral', '推荐'), ('event', '线下活动'), ('ad', '付费广告'), ('organic', '自然搜索')], default='website', max_length=20, verbose_name='来源渠道'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['stage'], name='marketing_l_stage_598744_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['country'], name='marketing_l_country_96ca7f_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['source'], name='marketing_l_source_3686ec_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorlog',
            index=models.Index(fields=['funnel_stage'], name='marketing_v_funnel__461ac2_idx'),
        ),
        migrations.AddField(
            model_name='contentengagement',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='marketing.visitorlog', verbose_name='关联访客'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='drip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='marketing.emaildrip', verbose_name='关联序列'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='marketing.lead', verbose_name='收件线索'),
        ),
        migrations.AddField(
            model_name='intentevent',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intents', to='marketing.campaign', verbose_name='来源活动'),
        ),
        migrations.AddField(
            model_name='intentevent',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intents', to='marketing.lead', verbose_name='关联线索'),
        ),
        migrations.AddField(
            model_name='intentevent',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intents', to='marketing.visitorlog', verbose_name='关联访客'),
        ),
        migrations.AddField(
            model_name='order',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='marketing.campaign', verbose_name='来源活动'),
        ),
        migrations.AddField(
            model_name='order',
            name='intent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='marketing.intentevent', verbose_name='关联意图'),
        ),
        migrations.AddField(
            model_name='order',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='marketing.lead', verbose_name='关联线索'),
        ),
        migrations.AddIndex(
            model_name='contentengagement',
            index=models.Index(fields=['visitor', 'engagement_type'], name='marketing_c_visitor_887789_idx'),
        ),
        migrations.AddIndex(
            model_name='contentengagement',
            index=models.Index(fields=['is_qualified'], name='marketing_c_is_qual_1a8cb3_idx'),
        ),
        migrations.AddIndex(
            model_name='intentevent',
            index=models.Index(fields=['intent_type'], name='marketing_i_intent__18bb59_idx'),
        ),
        migrations.AddIndex(
            model_name='intentevent',
            index=models.Index(fields=['is_completed'], name='marketing_i_is_comp_5e8700_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='marketing_o_order_n_7ac5d1_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['paid_at'], name='marketing_o_paid_at_b88b70_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['country'], name='marketing_o_country_21591c_idx'),
        ),
    ]
